version: "3.9"

services:
  db:
    image: postgres:16
    container_name: zombieland_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zombieland
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d zombieland"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app:
    build: .
    container_name: zombieland_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/zombieland
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - /app/node_modules

volumes:
  db_data: