server {
    resolver 127.0.0.11 valid=10s;
    listen 80;
    server_name vps-9089784f.vps.ovh.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}