server {
    listen 80;
    server_name vps-9089784f.vps.ovh.net;

    # Certbot challenge (OBLIGATOIRE)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirection vers HTTPS après installation du cert
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name vps-9089784f.vps.ovh.net;

    ssl_certificate /etc/letsencrypt/live/vps-9089784f.vps.ovh.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vps-9089784f.vps.ovh.net/privkey.pem;

    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}